Web/Controllers/EventController.cs
namespace AzureWebsitesDemo.Web.Controllers {
	using System.Collections.Generic;
	using System.Web.Mvc;
	using AzureWebsitesDemo.Data;

	public class EventController : Controller {
		private readonly EventRepository eventRepository = new EventRepository();
		private readonly QueueRepository queueRepository = new QueueRepository();

		public ActionResult Index() {
			List<Event> events = this.eventRepository.GetEvents();
			return this.View(events);
		}

		public ActionResult NewMessage(string Content) {
			this.queueRepository.AddMessage(Content);
			return this.RedirectToAction("Index");
		}

	}
}

Web/Controllers/HomeController.cs
namespace AzureWebsitesDemo.Web.Controllers {
	using System.Web.Mvc;
	using AzureWebsitesDemo.Data;

	public class HomeController : Controller {
		private readonly EventRepository eventRepository = new EventRepository();

		public ActionResult Index() {
			this.eventRepository.SaveEvent("Home page loaded");
			return this.View();
		}

		public ActionResult About() {
			this.ViewBag.Message = "The application description page.";

			return this.View();
		}

		public ActionResult Contact() {
			this.ViewBag.Message = "Your contact page.";

			return this.View();
		}
	}
}

Web/Controllers/QueueController.cs
namespace AzureWebsitesDemo.Web.Controllers {
	using System.Collections.Generic;
	using System.Web.Mvc;
	using AzureWebsitesDemo.Data;

	public class QueueController : Controller {
		private readonly QueueRepository queueRepository = new QueueRepository();

		public ActionResult Index() {
			List<string> messages = this.queueRepository.EmptyQueue();
			return this.View(messages);
		}

		public ActionResult NewMessage(string Content) {
			this.queueRepository.AddMessage(Content);
			return this.RedirectToAction("Index");
		}

	}
}

Web/Views/Event/Index.cshtml
@model List<Event>

@{
	ViewBag.Title = "Events";
}

<h2>@ViewBag.Title</h2>

<table class="table">
	<thead>
		<tr>
			<th>ID</th>
			<th>Date</th>
			<th>Description</th>
		</tr>
	</thead>
	<tbody>
		@foreach (Event e in Model) {
			<tr>
				<td>@e.EventId</td>
				<td>@e.EventDate.ToString("G")</td>
				<td>@e.Description</td>
			</tr>
		}
	</tbody>
</table>

@using (Html.BeginForm("NewMessage", "Event")) {
	<input type="text" name="Content" placeholder="Content" />
	<input type="submit" value="Add to Queue" />
}

Web/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Web/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="http://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Web/Views/Queue/Index.cshtml
@model List<string>

@{
	ViewBag.Title = "Queue Messages";
}

<h2>@ViewBag.Title</h2>

@if (Model.Count <= 0) {
	<p>Queue is empty</p>
} else {
	<ul>
		@foreach (string message in Model) {
			<li>@message</li>
		}
	</ul>
}

@using (Html.BeginForm("NewMessage", "Queue")) {
	<input type="text" name="Content" placeholder="Content" />
	<input type="submit" value="Add to Queue" />
}

Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
				@Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
			</div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
					<li>@Html.ActionLink("Contact", "Contact", "Home")</li>
					<li>@Html.ActionLink("Events", "Index", "Event")</li>
					<li>@Html.ActionLink("Queue", "Index", "Queue")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>